/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Bootloadable_1.h>
#include <Power_Up_LCD_Pin_1.h>
#include <Power_Up_LCD_Pin_1_aliases.h>
#include <Back_Light_On_P.h>
#include <Back_Light_On_P_aliases.h>
#include <Back_Light_On_N.h>
#include <Back_Light_On_N_aliases.h>
#include <LCD_Char.h>
#include <LED.h>
#include <LED_aliases.h>
#include <IR_REC.h>
#include <IR_REC_aliases.h>
#include <IR_Int.h>
#include <PWM_Timer.h>
#include <PWM_Int.h>
#include <Clock_1.h>
#include <LCD_Char_LCDPort.h>
#include <LCD_Char_LCDPort_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

