/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Bootloadable.h>
#include <Board_LED.h>
#include <Board_LED_aliases.h>
#include <IR_LED.h>
#include <IR_LED_aliases.h>
#include <SWL.h>
#include <SWL_aliases.h>
#include <SWL_Int.h>
#include <SWR.h>
#include <SWR_aliases.h>
#include <SWR_Int.h>
#include <SWB.h>
#include <SWB_aliases.h>
#include <SWB_Int.h>
#include <Left_LED_Green.h>
#include <Left_LED_Green_aliases.h>
#include <Right_LED_Green.h>
#include <Right_LED_Green_aliases.h>
#include <PWM_Right_LED_Red.h>
#include <clk_4kHz.h>
#include <PWM_Left_LED_Red.h>
#include <Left_LED_Red.h>
#include <Left_LED_Red_aliases.h>
#include <Right_LED_Red.h>
#include <Right_LED_Red_aliases.h>
#include <Left_LED_Blue.h>
#include <Left_LED_Blue_aliases.h>
#include <Right_LED_Blue.h>
#include <Right_LED_Blue_aliases.h>
#include <PWM_Organizer.h>
#include <ORG_Int.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

